###
//Status connection database
GET http://localhost:4000/ HTTP/1.1

//USER AUTHENTICATION
###
//Renew token
POST http://localhost:4000/user/token HTTP/1.1
content-type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwMDAwMSIsImZpcnN0X25hbWUiOiLguIjguLTguKPguKjguLHguIHguJTguLTguYwiLCJsYXN0X25hbWUiOiLguJTguYnguKfguIfguITguLPguIjguLHguJnguJfguKPguYwiLCJFbWFpbCI6IjQuMS5qaXJhc2FrQGdtYWlsLmNvbSIsInRlbCI6IjA5NDA3OTYxNzMiLCJpYXQiOjE2MTUzMTg1MTB9.eapjEkQoKWAzuYIcjTyPKxc5UGzaySlm1IwffAWxjvA"
}
###
//User Login
POST http://localhost:4000/user/login/ HTTP/1.1
content-type: application/json

{
    "email" : "4.1.jirasak@gmail.com",
    "password" : "abcdfe054"
}

###
//User Logout
DELETE http://localhost:4000/user/logout/ HTTP/1.1
content-type: application/json

{
    //refresh Token
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwMDAwMSIsImZpcnN0X25hbWUiOiLguIjguLTguKPguKjguLHguIHguJTguLTguYwiLCJsYXN0X25hbWUiOiLguJTguYnguKfguIfguITguLPguIjguLHguJnguJfguKPguYwiLCJFbWFpbCI6IjQuMS5qaXJhc2FrQGdtYWlsLmNvbSIsInRlbCI6IjA5NDA3OTYxNzMiLCJpYXQiOjE2MTU0MDUzNzR9.J32tFkcen5cFOdnISjPruQVbLfIlHqlxvmVkphaPhI0"
}

###
//Create user
POST http://localhost:4000/user/ HTTP/1.1
content-type: application/json

{
    "uid" : "00001",
    "first_name" : "จิรศักดิ์",
    "last_name" : "ด้วงคำจันทร์",
    "tel" : "0940796173",
    "email" : "4.1.jirasak@gmail.com",
    "password" : "abcdfe054"
}

###
//Delete user
DELETE http://localhost:4000/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwMDAwMSIsImZpcnN0X25hbWUiOiLguIjguLTguKPguKjguLHguIHguJTguLTguYwiLCJsYXN0X25hbWUiOiLguJTguYnguKfguIfguITguLPguIjguLHguJnguJfguKPguYwiLCJFbWFpbCI6IjQuMS5qaXJhc2FrQGdtYWlsLmNvbSIsInRlbCI6IjA5NDA3OTYxNzMiLCJpYXQiOjE2MTUzMTg3MzksImV4cCI6MTYxNTMxODc1OX0.mIjtpCGqGfpltJq0HxHrmJJk6ceE1GipASb7uJBXywY

###
//Update user
PUT http://localhost:4000/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwMDAwMSIsImZpcnN0X25hbWUiOiLguIjguLTguKPguKjguLHguIHguJTguLTguYwiLCJsYXN0X25hbWUiOiLguJTguYnguKfguIfguITguLPguIjguLHguJnguJfguKPguYwiLCJFbWFpbCI6IjQuMS5qaXJhc2FrQGdtYWlsLmNvbSIsInRlbCI6IjA5NDA3OTYxNzMiLCJpYXQiOjE2MTU0MDcwMjEsImV4cCI6MTYxNTQxMDYyMX0.4LUxF7ImRccL1ZHpIvyoyDmVX1ky0E4-qfXDBbPVf7k
Content-type: application/json

{
    "first_name" : "จิรศักดิ์",
    "last_name" : "ด้วงคำจันทร์",
    "tel" : "0894339804"
}

###
//Create Restaurant
POST http://localhost:4000/restaurant/ HTTP/1.1
content-type: application/json

{
    "rid" : "00001",
    "restaurant_name" : "USIT",
    "first_name" : "จิรศักดิ์",
    "last_name" : "ด้วงคำจันทร์",
    "tel" : "0940796173",
    "email" : "4.1.jirasak@gmail.com",
    "address" : "EN, Faculty of engineering",
    "minperq" : "1",
    "maxperq" : "6",
    "qperday" : "13",
    "description" : "Coffee Bar and Sleeping Zone for Hangerman.",
    "password" : "abcdfe054"
}